import "./globals.css";
import { Inter } from "next/font/google";

import { Nunito } from "next/font/google";

const mukta = Nunito({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={mukta.className} data-theme="">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
